
services:

  web:
    container_name: web
    build: ./project
    ports:
      - 8004:8000
    command: uvicorn fastapi_app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/usr/src/app
    env_file: ".env"
    # environment:
    #   - CELERY_BROKER_URL=redis://redis:6379/0
    #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    container_name: worker
    build: ./project
    command: celery -A selery_app.app:app worker --loglevel=info --logfile=logs/celery.log -P gevent
    volumes:
      - ./project:/usr/src/app
    env_file: ".env"
    # environment:
    #   - CELERY_BROKER_URL=redis://redis:6379/0
    #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  beat:
    container_name: beat
    build: ./project
    command: celery -A selery_app.app:app beat --loglevel=info --logfile=logs/beat.log
    volumes:
      - ./project:/usr/src/app
    env_file: ".env"
    # environment:
    #   - CELERY_BROKER_URL=redis://redis:6379/0
    #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - worker
      
  dashboard:
    build: ./project
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    env_file: ".env"
    # environment:
    #   - CELERY_BROKER_URL=redis://redis:6379/0
    #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
      - beat

  redis:
    image: redis:latest
    container_name: redis

